# Generated by Django 5.2.5 on 2025-08-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=150)),
                ('emp_age', models.IntegerField()),
                ('emp_location', models.CharField(max_length=150)),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
